In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("spam.csv")

In [6]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [9]:
df['Spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [14]:
df.shape

(5572, 3)

In [13]:
df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.Spam, test_size = 0.2)

In [18]:
X_train.shape, X_test.shape

((4457,), (1115,))

In [20]:
type(X_train)

pandas.core.series.Series

In [24]:
X_train[:4]

3276    Hurry home u big butt. Hang up on your last ca...
5076    This is the 2nd attempt to contract U, you hav...
4104    U have a secret admirer who is looking 2 make ...
408     Hello! Good week? Fancy a drink or something l...
Name: Message, dtype: object

In [25]:
type(y_train)

pandas.core.series.Series

In [26]:
y_train[:4]

3276    0
5076    1
4104    1
408     0
Name: Spam, dtype: int64

In [27]:
X_train.values

array(["Hurry home u big butt. Hang up on your last caller if u have to. Food is done and I'm starving. Don't ask what I cooked.",
       'This is the 2nd attempt to contract U, you have won this weeks top prize of either £1000 cash or £200 prize. Just call 09066361921',
       'U have a secret admirer who is looking 2 make contact with U-find out who they R*reveal who thinks UR so special-call on 09058094599',
       ...,
       'I will lick up every drop :) are you ready to use your mouth as well?',
       "Great. I was getting worried about you. Just know that a wonderful and caring person like you will have only the best in life. Know that u r wonderful and God's love is yours.",
       'U free on sat rite? U wan 2 watch infernal affairs wif me n darren n mayb xy?'],
      dtype=object)

In [44]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7751 sparse matrix of type '<class 'numpy.int64'>'
	with 59110 stored elements in Compressed Sparse Row format>

In [33]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [37]:
v.get_feature_names_out()[3556]

'hurry'

In [ ]:
v.vocabulary_

In [39]:
X_train_np = X_train_cv.toarray()
X_train_np[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [41]:
np.where(X_train_np[0] != 0)

(array([ 956, 1095, 1355, 1584, 1623, 2006, 2402, 2404, 2922, 3314, 3355,
        3467, 3556, 3597, 3743, 4029, 4944, 6455, 6932, 7186, 7478, 7716]),)

In [46]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [48]:
X_test_cv = v.transform(X_test)

In [50]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       964
           1       0.97      0.95      0.96       151

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [51]:
#Training the same model using pipeline

In [52]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [56]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [57]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       964
           1       0.97      0.95      0.96       151

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

